# wrangler.toml
name = "saizen"
main = "src/index.ts"
compatibility_date = "2025-03-27"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./public"

[observability]
enabled = true

[[kv_namespaces]]
binding = "GEMINI_KEYS_KV"
id = "d0d542a069bd4449b6996fd25e26a94f"

[[kv_namespaces]]
binding = "WORKER_CONFIG_KV"
id = "d0d542a069bd4449b6996fd25e26a94f"
